# ─── CONFIGURATION ────────────────────────────────────────────────────────────
# Centralizes all application constants.

# OAuth scopes requested from the Gmail API
SCOPES = [
    "https://www.googleapis.com/auth/gmail.readonly",
    "https://www.googleapis.com/auth/gmail.send",
    "https://www.googleapis.com/auth/gmail.modify",
    "https://www.googleapis.com/auth/gmail.labels",
    "https://www.googleapis.com/auth/gmail.settings.basic",  # required for filter management
]

# OAuth files generated by Google Cloud Console
CREDENTIALS_FILE = "credentials.json"   # Download from Google Cloud Console
TOKEN_FILE       = "token.json"         # Generated automatically after the first login

# Index of the Gmail account in the browser (0 = first account, 1 = second, etc.)
# Change this value if "Open in browser" opens the wrong account.
GMAIL_ACCOUNT_INDEX = 1
